### ISSUE TITLE
Regex chars in process name

### ISSUE THREAD

**Issue by freehuntx** [xsellier/node-ps#5]
If you have a processname like "Notepad++.exe", this library will fail.
It tries to parse it as regex.

**Comment by xsellier** [comment]
@freehuntx I suggest you to use a regex escaper (fyi: https://codereview.stackexchange.com/questions/153691/escape-user-input-for-use-in-js-regex).

Here an example:

```javascript
var psMan = require("ps-man")

// Filter by name
var options = {
  name: escapeRegExp('notepad++.exe')
};

function escapeRegExp(string){
  return string.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'); // $& means the whole matched string
}

psMan.list(options, function(err, result) {
  console.log(err)
  console.log(result)
});
```
